### PR TITLE
fix: from multiline output to single line 

### PR DESCRIPTION
**Pull request by jsmvaldivia**
Currently output is being output as a multiline output making unusable for GHA

### CODE REVIEW

**Comment by crqrdotcom** [comment]
I know we've spoken about this offline but TBH I can't remember exactly the reason why we have to do this. If the multiline output is a problem, can't we just use `json.Marshal` instead of introducing a new dependency?

**Comment by jsmvaldivia** [comment]
Multiline is the problem but `json.Marshal` won't do it. The output we get from the AWS AppConfig request is already a string. As we are not manipulating it and returning it as it is we need a way that the output is not multiline. Just in a single line

**Comment by crqrdotcom** [comment]
> Multiline is the problem but `json.Marshal` won't do it. The output we get from the AWS AppConfig request is already a string. As we are not manipulating it and returning it as it is we need a way that the output is not multiline. Just in a single line

Have you tried `strings.Replace(str, "\n", "", -1)`? Maybe it does the trick 🪄

**Comment by jsmvaldivia** [comment]
@crqra I took a different route, pls check, I am no longer outputting configurations.

**Review by crqrdotcom — APPROVED** [review]
LGTM! 👍🏼

**Pull request merged**
